######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "/media/leon/Data/EMB3/git/Emb/PongPowerPlayer.srcs/sources_1/edk/microblaze"
if { [xload new microblaze.xmp] != 0 } {
  exit -1
}
xset arch aspartan6
xset dev xa6slx45
xset package fgg484
xset speedgrade -3

xset binfo 

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl vhdl
save proj
exit
