# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "/opt/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "/home/dimx/Documents/Uni/Embedded3/PongPowerPlayer/PongPowerPlayer.srcs/sources_1/ip/cg_lin_index_map.xml"

set cgProjectPath "/home/dimx/Documents/Uni/Embedded3/PongPowerPlayer/PongPowerPlayer.srcs/sources_1/ip/clk_wiz_v3_6_0/coregen.cgc"

set ipFile "/home/dimx/Documents/Uni/Embedded3/PongPowerPlayer/PongPowerPlayer.srcs/sources_1/ip/clk_wiz_v3_6_0/clk_wiz_v3_6_0.xco"

set ipName "clk_wiz_v3_6_0"

set vlnv "xilinx.com:ip:clk_wiz:3.6"

set cgPartSpec "xa6slx45-3fgg484"

set bomFilePath "/home/dimx/Documents/Uni/Embedded3/PongPowerPlayer/PongPowerPlayer.srcs/sources_1/ip/clk_wiz_v3_6_0/pa_cg_bom.xml"

set hdlType "VHDL"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "/opt/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

